import "./globals.css";
import { Navbar } from "@/components/navbar";
import Link from "next/link";
import localFont from "next/font/local";
import type { Metadata } from "next";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container mx-auto px-4 text-pretty">
          <Navbar />
          {children}
          <footer className="container">
            <p>
              &copy; 2024{" "}
              <Link
                href="https://ryanfurrer.com"
                target="_blank"
                rel="noopener noreferrer"
              >
                Ryan Furrer
              </Link>
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
